In [11]:
import sklearn 

In [12]:
import pandas as pd
data = pd.read_csv("/Users/annie/Documents/GitHub/Python-libraries-playground/datasets/big_mart_sales.csv")
data.head(3)

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility    Item_Type  \
0           FDA15         9.30          Low Fat         0.016047        Dairy   
1           DRC01         5.92          Regular         0.019278  Soft Drinks   
2           FDN15        17.50          Low Fat         0.016760         Meat   

   Item_MRP Outlet_Identifier  Outlet_Establishment_Year Outlet_Size  \
0  249.8092            OUT049                       1999      Medium   
1   48.2692            OUT018                       2009      Medium   
2  141.6180            OUT049                       1999      Medium   

  Outlet_Location_Type        Outlet_Type  Item_Outlet_Sales  
0               Tier 1  Supermarket Type1          3735.1380  
1               Tier 3  Supermarket Type2           443.4228  
2               Tier 1  Supermarket Type1          2097.2700

In [13]:
data.isnull().sum()

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [14]:
from sklearn.impute import SimpleImputer

In [15]:
impute_item_weight = SimpleImputer(strategy = "mean")
impute_outlet_size = SimpleImputer(strategy = "most_frequent")

Why imputer object needs to fit before transforming the missing values with some statistics?

The imputer fills missing values with some  statistics ie. mean, median, most_frequent etc. of the data, to avoid data leavage during cross-validation (happens when your training data contains information about the target, but similar data will not be available when the model is used for prediction), it computes the statistic on the train data during the fit, stores it and uses it on the test data during the transform.

In [16]:
from sklearn.impute import SimpleImputer
import numpy as np
obj = SimpleImputer(strategy = 'mean')
obj.fit([[1, 2, 3], [2, 3, 4]])
print(obj.statistics_)

X = obj.transform([[4, np.nan, 6], [5, 6, np.nan]])
print(X)

[1.5 2.5 3.5]
[[4.  2.5 6. ]
 [5.  6.  3.5]]


We can do both steps in oe if the train and test data are identical, using fir_transform

In [17]:
X = obj.fit_transform([[1, 2, np.nan], [2, 3, 4], [3, 4, 5]])
print(X)

[[1.  2.  4.5]
 [2.  3.  4. ]
 [3.  4.  5. ]]


In [18]:
impute_item_weight.fit(data[["Item_Weight"]])
data.Item_Weight = impute_item_weight.transform(data[["Item_Weight"]])

data.Outlet_Size = impute_outlet_size.fit_transform(data[["Outlet_Size"]])

print(data.isnull().sum())

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
Item_Outlet_Sales            0
dtype: int64
